name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Fortran Package Manager
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install curl development headers
      if: contains( matrix.os, 'ubuntu' )
      run: sudo apt install -y libcurl4-openssl-dev
    - name: Build with GCC
      run: fpm build
    - name: Test with GCC
      run: fpm test
